export const urls = {
  main: '/main',
  subjects: '/',
  courses: '/courses',
  contacts: '/contacts',
  user: '/me',
  auth: '/auth',
  registration: '/registration',
  mainPersonal: '/me/mainPersonal',
  schedule: '/me/schedule',
  news: '/me/news',
  myData: '/me/myData',
  homework: '/me/homework',
  pupils: '/me/pupils',
  shop: '/me/shop',
  myCourses: '/me/courses',
}
