export const urls = {
  main: '/main',
  subjects: '/',
  courses: '/courses',
  contacts: '/contacts',
  user: '/me',
  auth: '/auth',
  registration: '/registration',
  mainPersonal: '/me/mainPersonal',
  schedule: '/me/schedule',
  news: '/me/news',
  myData: '/me/mydata',
  homework: '/me/homework',
  pupils: '/me/pupils',
  shop: '/me/shop',
  myCourses: '/me/courses',
  myCoursesDeatil: '/me/courses',
  teachers: '/me/teachers',
  teacherCreation: '/me/teachers/create',
  reviews: '/me/reviews'
}
